version: '3.8'

services:
  web:
    build: ./saufhaengerle
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./saufhaengerle:/home/app/web/
    env_file:
      - ./saufhaengerle/.env
    depends_on:
      - db

volumes:
  postgres_data:
