version: '3.8'

services:
  web:
    build: ./saufhaengerle
    command: gunicorn saufhaengerle.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./saufhaengerle/.env
    depends_on:
      - db

volumes:
  postgres_data:
