version: '3.8'

services:
  web:
    build: ./saufhaengerle
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./saufhaengerle:/home/app/web/
    env_file:
      - ./saufhaengerle/.env.dev

  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  node-red:
    image: nodered/node-red:2.2.2-12
    ports:
      - 1880:1880
    volumes:
      - nodered_data:/data

  larynx:
    image: rhasspy/larynx:de-de
    ports:
      - 5002:5002

  flask-larynx:
    build: ./flask-larynx
    ports:
      - 1349:1349
    volumes:
      - ./flask-larynx:/home/app/web/

volumes:
  postgres_data:
  nodered_data:
