# Generated by Django 4.0.4 on 2022-07-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='product',
            field=models.CharField(default='Bier', max_length=100),
        ),
    ]
