# Generated by Django 4.0.4 on 2022-07-26 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fingerprints', '0004_alter_fingerprint_finger_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lock', 'lock'), ('unlock', 'unlock')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fingerprints.fingerprint')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
