# Generated by Django 4.0.4 on 2022-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_type', models.CharField(choices=[('LEFT_THUMB', 'Left thump'), ('LEFT_INDEX', 'Left index'), ('LEFT_MIDDLE', 'Left middle'), ('LEFT_RING', 'Left ring'), ('LEFT_PINKY', 'Left pinky'), ('RIGHT_THUMB', 'Right thump'), ('RIGHT_INDEX', 'Right index'), ('RIGHT_MIDDLE', 'Right middle'), ('RIGHT_RING', 'Right ring'), ('RIGHT_PINKY', 'Right pinky')], max_length=12)),
            ],
        ),
    ]
