# Generated by Django 4.0.4 on 2022-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0003_fingerprint_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='finger_type',
            field=models.CharField(choices=[('LEFT_THUMB', 'Left thumb'), ('LEFT_INDEX', 'Left index'), ('LEFT_MIDDLE', 'Left middle'), ('LEFT_RING', 'Left ring'), ('LEFT_PINKY', 'Left pinky'), ('RIGHT_THUMB', 'Right thumb'), ('RIGHT_INDEX', 'Right index'), ('RIGHT_MIDDLE', 'Right middle'), ('RIGHT_RING', 'Right ring'), ('RIGHT_PINKY', 'Right pinky')], max_length=12),
        ),
    ]
