# Generated by Django 4.0.4 on 2022-07-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scale', '0001_initial'),
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity_ml', models.FloatField()),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_event', to='actions.event')),
                ('start_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_measurement', to='scale.measurement')),
                ('stop_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_measurement', to='scale.measurement')),
                ('unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_event', to='actions.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
