# Generated by Django 4.0.4 on 2022-07-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
        ('taps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scale.scale'),
        ),
    ]
